[metadata]
name = apytizer
version = attr: apytizer.__version__
author = Sean Sullivan
author_email = seansullivan@seanmedia.ca
description = Implement wrappers quickly for REST APIs
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/seanssullivan/apytizer
download_url = https://github.com/seanssullivan/apytizer/archive/refs/tags/v0.0.1-alpha.tar.gz
project_urls =
    Bug Tracker = https://github.com/seanssullivan/apytizer/issues
classifiers =
    Intended Audience :: Developers
    License :: OSI Approved :: Apache Software License
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Natural Language :: English
    Operating System :: OS Independent

[options]
python_requires = >=3.9
package_dir =
    = src
packages = find:
install_requires =
    cachetools
    requests

[options.packages.find]
where = src
exclude =
    apytizer.factories*
    apytizer.managers*
    apytizer.mappers*
    apytizer.repositories*
    apytizer.states*

[options.extras_require]
docs =
    sphinx>=2.0.0
testing =
    cachetools
    coverage
    Flask
    pytest
    pytest-cov
    requests

[build_sphinx]
project = Apytizer
version = attr: apytizer.__version__
source-dir = docs
build-dir = build
builder = html
