[tox]
envlist = py39
isolated_build = True

[testenv]
description = run tests with pytest under {basepython}
deps=
    coverage
    pytest
    pytest-cov
	pytest-env
extras = testing
commands =
    coverage erase
    coverage run -m pytest --tb=short
    coverage report --omit='.tox/*'
    coverage html --omit='.tox/*'
setenv =
    ENV = tox